---

- name: add apt-key
  apt_key:
    id: 74D9DBB5
    url: https://prosody.im/files/prosody-debian-packages.key
    state: present
  become: yes

- name: add repository
  apt_repository:
    repo: deb https://packages.prosody.im/debian {{ ansible_distribution_release }} main
    state: present
    update_cache: yes
  become: yes

- name: install prosody
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - lua-event
    - lua-dbi-mysql
    - lua-zlib
    - prosody
  become: yes
